services:
  solving-occlusion:
    container_name: solving-occlusion
    image: mstoelzle/solving-occlusion:latest
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,display
    runtime: nvidia
    volumes:
      - ./data:/workspace/solving-occlusion/data